### ISSUE TITLE
Manuel reload does not reset timer

### ISSUE THREAD

**Issue by stefanengel** [stefanengel/Lumina#1]
When doing a manual refresh, the running timer is not reset, so it might happen that an automatic refresh happens immediately after a manual refresh.

**Comment by dehlen** [comment]
While you are refactoring this part of the code / fixing the bug: You could probably use 
`let timer = Timer.publish(every: 1, on: .main, in: .common).autoconnect()` to create a timer. The nice thing about this is, that you get a Publisher which you can easily cancel.

**Comment by dehlen** [comment]
I created a PR to fix this issue. See #18.
