### ISSUE TITLE
Scope of this project?

### ISSUE THREAD

**Issue by dehlen** [stefanengel/Lumina#15]
Hey, could you elaborate what you think is scope of this project?
I am thinking about detail views of all the builds for a given branch. Also it might be able to download artifacts of this build in order to deploy apps directly to the Simulator/Phone/Emulator. I think this project aims to be a build monitor so this functionality might be a bit out of scope. Especially considering other third party providers. Just wanted to hear your thoughts on this topic.

**Comment by stefanengel** [comment]
Hi there,

it took me a long time to figure out what the true scope of this project is, but finally it became clear to me.
Lumina is a native build monitor app for macOS that currently supports projects on Bitrise. There is an abstraction layer that theoretically allows the integration of other CI systems, but implementing other providers is currently not in scope.

The development of Lumina is mainly driven by the requirements that users have. The main goal is to regain an overview of whats going on at the build pipeline. It is intended as an app that developers run on their local macs to see the builds that really matter to them.
