### ISSUE TITLE
[Feature Request] Add open-window to toolbar menu

### ISSUE THREAD

**Issue by NiciDieNase** [stefanengel/Lumina#5]
Right now I can only open the builds on bitrise from the toolbar-menu. 
It would be nice if I could also open the window from there.

**Comment by dehlen** [comment]
Could you elaborate on what exactly you mean? You can open the builds on Bitrise by just clicking on one of them.

**Comment by dehlen** [comment]
Nevermind I see what you are referring to. You want a Menu Item in the StatusBar Application to open the main window of Lumina. I'll try to make a PR. Lets see what @stefanengel says about adding this kind of functionality.

**Comment by dehlen** [comment]
I added a PR. See #20.
